stages:
  process_data:
    cmd: python src/process_data.py
    deps:
    - config/main.yaml
    - config/process
    - data/raw
    - src/process_data.py
    outs:
    - data/intermediate:
        persist: true
  segment:
    cmd: python src/segment.py
    deps:
    - config/main.yaml
    - config/segment
    - data/intermediate
    - src/segment.py
    outs:
    - data/final:
        persist: true
    - image:
        persist: true
