[tool.poetry]
name = "customer_segmentation"
version = "0.1.0"
description = ""
authors = ["khuyentran1401 <khuyentran1476@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = ">=1.14.3,<1.21.0"
matplotlib = "^3.5.1"
seaborn = "^0.11.2"
scikit-learn = "^1.0.2"
hydra-core = "^1.1.1"
dvc = "^2.9.3"
yellowbrick = "^1.3.post1"
pandas = "<1.3.5"
wandb = "^0.12.9"
bentoml = "1.0.0a3"
prefect = "^0.15.13"
pydantic = "^1.9.0"
streamlit = "^1.5.1"
pygit2 = "1.8.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pre-commit = "^2.17.0"

[virtualenvs]
create = true
in-project = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
